services:
  rest-api:
    build: ./docker/api-server
    restart: always
    container_name: rest-api
    volumes:
      - ./src:/opt/restapi/src
    ports:
      - 5056:5056

  airflow:
    build: ./docker/airflow
    restart: always
    container_name: airflow
    volumes:
      - ./src/airflow-dags:/opt/airflow/dags
      - ./src:/opt/airflow/dags/src
    ports:
      - 8000:8080

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: ./docker/producer
    depends_on:
      - zookeeper
      - kafka
    restart: always
    container_name: producer
    volumes:
      - ./src:/opt/producer/src

  consumer:
    build: ./docker/consumer
    restart: always
    depends_on:
      - zookeeper
      - kafka
    container_name: consumer
    volumes:
      - ./src:/opt/consumer/src





